# KHO TỪ ĐIỂN ĐA NGÔN NGỮ (Tách ra đây cho gọn app.py)
DICTIONARY = {
    'vi': {
        'export_task': 'THIẾT LẬP XUẤT KHO',
        'export_mode': 'LOẠI HÌNH XUẤT',
        'mode_prod': '🏭 Xuất cho Sản Xuất (PO)',
        'mode_scrap': '🗑️ Xuất Hủy / Thanh Lý',
        'mode_rtv': '🚚 Xuất Trả NCC (RTV)',
        'mode_other': '📦 Xuất Khác / Nội bộ',
        'select_po': 'CHỌN LỆNH SX (PO)',
        'scan_po_ph': 'Quét hoặc Chọn PO...',
        'note_reason': 'GHI CHÚ / LÝ DO',
        'note_ph': 'Vd: Hết hạn, Hư hỏng...',
        'progress_title': 'TIẾN ĐỘ PICKING',
        'session_hist': 'LỊCH SỬ PHIÊN',
        'saved': 'Đã lưu',
        'clear_hist': 'Xóa lịch sử',
        'scan_ph': 'Quét mã vạch hoặc nhập SKU...',
        'waiting': 'Sẵn sàng quét...',
        'stock': 'Tồn',
        'expiry': 'Hạn dùng',
        'completed': 'ĐÃ HOÀN THÀNH!',
        'completed_msg': 'Sản phẩm này đã lấy đủ số lượng.',
        'select_batch': 'CHỌN LÔ (BATCH)',
        'no_batch': 'Không có thông tin lô',
        'qty': 'SỐ LƯỢNG',
        'btn_confirm': 'XUẤT KHO',
        'priority': 'Ưu tiên',
        'empty_po': 'Vui lòng chọn Lệnh Sản Xuất (PO)',
        'empty_po_sub': 'Chọn PO từ cột bên trái để bắt đầu.',
        'login_title': 'ĐĂNG NHẬP HỆ THỐNG',
        'username': 'Tên đăng nhập',
        'password': 'Mật khẩu',
        'btn_login': 'ĐĂNG NHẬP',
        'login_msg': 'Vui lòng nhập tài khoản để tiếp tục',
        'wrong_pass': 'Sai tên đăng nhập hoặc mật khẩu!'
    },
    'en': {
        'export_task': 'EXPORT TASK CONFIG',
        'export_mode': 'EXPORT MODE',
        'mode_prod': '🏭 Production (PO)',
        'mode_scrap': '🗑️ Scrap / Disposal',
        'mode_rtv': '🚚 Return to Vendor (RTV)',
        'mode_other': '📦 Miscellaneous / Other',
        'select_po': 'SELECT PO / WO',
        'scan_po_ph': 'Scan or Select PO...',
        'note_reason': 'NOTE / REASON',
        'note_ph': 'e.g. Expired, Damaged...',
        'progress_title': 'PICKING PROGRESS',
        'session_hist': 'SESSION HISTORY',
        'saved': 'Saved',
        'clear_hist': 'Clear History',
        'scan_ph': 'Scan barcode or enter SKU...',
        'waiting': 'Waiting for scan...',
        'stock': 'Stock',
        'expiry': 'Expiry',
        'completed': 'COMPLETED!',
        'completed_msg': 'Item fully picked. No action needed.',
        'select_batch': 'SELECT BATCH',
        'no_batch': 'No Batch Info',
        'qty': 'QUANTITY',
        'btn_confirm': 'CONFIRM OUT',
        'priority': 'Priority',
        'empty_po': 'Please select a Production Order (PO)',
        'empty_po_sub': 'Choose a PO from the left panel to start.',
        'login_title': 'SYSTEM LOGIN',
        'username': 'Username',
        'password': 'Password',
        'btn_login': 'LOGIN',
        'login_msg': 'Please enter your credentials to continue',
        'wrong_pass': 'Invalid username or password!'
    },
    'zh': {
        'export_task': '出库任务设置',
        'export_mode': '出库模式',
        'mode_prod': '🏭 生产领料 (PO)',
        'mode_scrap': '🗑️ 报废 / 清理',
        'mode_rtv': '🚚 退货给供应商 (RTV)',
        'mode_other': '📦 其他 / 内部领用',
        'select_po': '选择生产工单 (PO)',
        'scan_po_ph': '扫描或选择 PO...',
        'note_reason': '备注 / 原因',
        'note_ph': '例如：过期，损坏...',
        'progress_title': '拣货进度',
        'session_hist': '本次操作记录',
        'saved': '已保存',
        'clear_hist': '清除记录',
        'scan_ph': '扫描条码或输入 SKU...',
        'waiting': '等待扫描...',
        'stock': '库存',
        'expiry': '有效期',
        'completed': '已完成！',
        'completed_msg': '该商品已拣货完毕。',
        'select_batch': '选择批次 (Batch)',
        'no_batch': '无批次信息',
        'qty': '数量',
        'btn_confirm': '确认出库',
        'priority': '优先',
        'empty_po': '请选择生产工单 (PO)',
        'empty_po_sub': '请从左侧面板选择 PO 以开始。',
        'login_title': '系统登录',
        'username': '用户名',
        'password': '密码',
        'btn_login': '登录',
        'login_msg': '请登录以继续操作',
        'wrong_pass': '用户名或密码错误！'
    }
}